name: Metrics

on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * 1"}]

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: Nasi2000
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Novosibirsk
          commit_message: "chore: update isocalendar"
          output_action: commit
          committer_branch: main
          
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_colors: rainbow
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
